### ISSUE TITLE
Raw Transaction Hex for Txn Hash for Binance Smart Chain

### ISSUE THREAD

**Issue by Web3Paradise** [rebryk/profanity-brute-force#14]
Does anyone know how to get Raw Transaction Hex for Txn Hash on Binance Smart Chain (BSC)?  On Ethereum it's easy to do this with etherscan but on BSC where do we find the Raw Transaction Hex from a TX on BSC SCAN to generate the public Key? 
Is there a tool to get the public Key for wallet only used on Binance Smart Chain?

**Comment by ghost** [comment]
If you can share the txn I can help

**Comment by Web3Paradise** [comment]
> If you can share the txn I can help

@babytether111 

Would be great if you take a random tx from the explorer and show us the process :)

**Comment by b006** [comment]
just use the python web3 library. theres a get_raw_transaction function

**Comment by Web3Paradise** [comment]
> just use the python web3 library. theres a get_raw_transaction function

Thank you for your answer!

**Comment by ghost** [comment]
this code has worked well for me:

import web3
from eth_account._utils.signing import extract_chain_id, to_standard_v
from eth_account._utils.legacy_transactions import serializable_unsigned_transaction_from_dict

w3 = web3.Web3(web3.HTTPProvider(""))
tx = w3.eth.get_transaction("")
tx = dict(tx)

type_0_keys = ['chainId', 'gas', 'gasPrice', 'nonce', 'to', 'value']
type_1_keys = ["to",
    "nonce",
    "value",
    "gas",
    'gasPrice',
    "chainId",
    "type"]
type_2_keys = ["to",
    "nonce",
    "value",
    "gas",
    "chainId",
    "maxFeePerGas",
    "maxPriorityFeePerGas",
    "type"]

s = w3.eth.account._keys.Signature(vrs=(
    to_standard_v(extract_chain_id(tx["v"])[1]),
    w3.to_int(tx["r"]),
    w3.to_int(tx["s"])
))

if tx["type"] == 0:
    keys_to_get = type_0_keys
elif tx["type"] == 1:
    keys_to_get = type_1_keys
elif tx["type"] == 2:
    keys_to_get = type_2_keys

if "chainId" not in tx:
    tx["chainId"] = 1

tt = {k:tx[k] for k in keys_to_get}
tt["data"] = tx["input"]

ut = serializable_unsigned_transaction_from_dict(tt)

public_key = s.recover_public_key_from_msg_hash(ut.hash())

if hasattr(public_key, 'to_hex'):
    public_key_hex = public_key.to_hex()
else:
    public_key_bytes = public_key.to_bytes()
    public_key_hex = public_key_bytes.hex()

print(public_key_hex)

**Comment by Web3Paradise** [comment]
> this code has worked well for me:
> 
> import web3 from eth_account._utils.signing import extract_chain_id, to_standard_v from eth_account._utils.legacy_transactions import serializable_unsigned_transaction_from_dict
> 
> w3 = web3.Web3(web3.HTTPProvider("")) tx = w3.eth.get_transaction("") tx = dict(tx)
> 
> type_0_keys = ['chainId', 'gas', 'gasPrice', 'nonce', 'to', 'value'] type_1_keys = ["to", "nonce", "value", "gas", 'gasPrice', "chainId", "type"] type_2_keys = ["to", "nonce", "value", "gas", "chainId", "maxFeePerGas", "maxPriorityFeePerGas", "type"]
> 
> s = w3.eth.account._keys.Signature(vrs=( to_standard_v(extract_chain_id(tx["v"])[1]), w3.to_int(tx["r"]), w3.to_int(tx["s"]) ))
> 
> if tx["type"] == 0: keys_to_get = type_0_keys elif tx["type"] == 1: keys_to_get = type_1_keys elif tx["type"] == 2: keys_to_get = type_2_keys
> 
> if "chainId" not in tx: tx["chainId"] = 1
> 
> tt = {k:tx[k] for k in keys_to_get} tt["data"] = tx["input"]
> 
> ut = serializable_unsigned_transaction_from_dict(tt)
> 
> public_key = s.recover_public_key_from_msg_hash(ut.hash())
> 
> if hasattr(public_key, 'to_hex'): public_key_hex = public_key.to_hex() else: public_key_bytes = public_key.to_bytes() public_key_hex = public_key_bytes.hex()
> 
> print(public_key_hex)

Thank you very much! I appreciated your help
