### ISSUE TITLE
Speed on Laptop RTX 2060

### ISSUE THREAD

**Issue by stevealexrs** [rebryk/profanity-brute-force#16]
Is it normal that it runs at around 2 MH/s on RTX 2060 Laptop? I use the default option on README.

**Comment by stevealexrs** [comment]
I tried the original profanity tool and it runs at around 200 MH/s

**Comment by ytrezq** [comment]
@stevealexrs : it seems he is using 32 bits integers for his multiprecision arithmetics. And in a naïve alghoritmic way (compared to ɢᴍᴘ on ᴄᴘᴜ).

**Comment by stevealexrs** [comment]
After troubleshooting for a while, the speed doesn't even appear anymore. The fan is running but the progress bar isn't there. I removed all files and clone the repo again but the problem persists. 

I am using Windows and it requires to 2 changes to compile. The [unsigned int](https://github.com/rebryk/profanity-brute-force/issues/5) and removing the whole CL_DEVICE_TOPOLOGY_AMD block in getUniqueDeviceIdentifier. 

It doesn't work in my dual boot ubuntu linux too. [Someone With Linux](https://github.com/rebryk/profanity-brute-force/issues/8)

**Comment by ytrezq** [comment]
@stevealexrs : Windows is a different ᴀʙɪ even compared to Linux vs Osx. I think ints are 16‑bits… I have a running Linux binary that detects nothing : even with the command line of the Readme. 

We don’t even know the OpenCl version being used as it needs to be declared outside Apple. A compiler warning is generated for OpenCl version 3 but it states that it should be declared.

**Comment by stevealexrs** [comment]
> After troubleshooting for a while, the speed doesn't even appear anymore. The fan is running but the progress bar isn't there. I removed all files and clone the repo again but the problem persists.

This progress bar is shown on Windows on my first run. My laptop has a mux switch that let me choose between dGPU or both iGPU and dGPU (hybrid mode). The original setting was hybrid mode. Later I switched to dGPU only mode to see if the performance is different. Then I switched back to hybrid mode but the progress bar disappeared. It reappeared after I switched to dGPU only mode again. Weird bug.

**Comment by stevealexrs** [comment]
> We don’t even know the OpenCl version being used as it needs to be declared outside Apple…

When I compile it with nvidia library, it says _Defaulting to 300 (OpenCL 3.0)_

**Comment by ytrezq** [comment]
> > After troubleshooting for a while, the speed doesn't even appear anymore. The fan is running but the progress bar isn't there. I removed all files and clone the repo again but the problem persists.
> 
> This progress bar is shown on Windows on my first run. My laptop has a mux switch that let me choose between dGPU or both iGPU and dGPU (hybrid mode). The original setting was hybrid mode. Later I switched to dGPU only mode to see if the performance is different. Then I switched back to hybrid mode but the progress bar disappeared. It reappeared after I switched to dGPU only mode again. Weird bug.

No. you ll just switch to a gpu where memory wasn t initialized (initialization step).

**Comment by stevealexrs** [comment]
> No. you ll just switch to a gpu where memory wasn t initialized (initialization step).

I use --skip arg when there are 2 gpu. 
When I run the same command _profanity.x64 --benchmark --skip 0_ on both original profanity and this brute force tool, the original prints this and continues to run:
```
Mode: benchmark
Target: Address
Devices:
  GPU1: NVIDIA GeForce RTX 2060, 6442123264 bytes available, 30 compute units (precompiled = yes)

Initializing OpenCL...
  Creating context...OK
  Loading kernel from binary...OK
  Building program...OK

Initializing devices...
  This should take less than a minute. The number of objects initialized on each
  device is equal to inverse-size * inverse-multiple. To lower
  initialization time (and memory footprint) I suggest lowering the
  inverse-multiple first. You can do this via the -I switch. Do note that
  this might negatively impact your performance.

  GPU1 initialized

Initialization time: 3 seconds
Running...
  Always verify that a private key generated by this program corresponds to the
  public key printed by importing it to a wallet of your choice. This program
  like any software might contain bugs and it does by design cut corners to
  improve overall performance.

Total: 195.446 MH/s - GPU1: 195.446 MH/s
  ```
  while this brute force tool prints the same thing minus last line _**Total: 195.446 MH/s - GPU1: 195.446 MH/s**_  and stops. Maybe skip arg is somehow broken under certain condition.

**Comment by stevealexrs** [comment]
> while this brute force tool prints the same thing minus last line _**Total: 195.446 MH/s - GPU1: 195.446 MH/s**_ and stops. Maybe skip arg is somehow broken under certain condition.

I figure out the cause of this bug, the author changed the printSpeed() code quite a bit and it skips GPU with m_index = 0(why??). Initially my nvidia GPU was index 0, intel GPU was index 1, that's why the speed is shown, then at some point intel becomes GPU0 and nvidia becomes GPU1. Not sure the exact flow but it works after I remove the skip code.

**Comment by ytrezq** [comment]
> > while this brute force tool prints the same thing minus last line _**Total: 195.446 MH/s - GPU1: 195.446 MH/s**_ and stops. Maybe skip arg is somehow broken under certain condition.
> 
> I figure out the cause of this bug, the author changed the printSpeed() code quite a bit and it skips GPU with m_index = 0(why??). Initially my nvidia GPU was index 0, intel GPU was index 1, that's why the speed is shown, then at some point intel becomes GPU0 and nvidia becomes GPU1. Not sure the exact flow but it works after I remove the skip code.

Please submit a pull request.

**Comment by stevealexrs** [comment]
Not sure if there is any side effect, I will wait until I successfully run the whole thing. It will take me around 80 hours to run all 8 batches with default options. I don't understand why rtx 2060(mobile) is so slow compared to apple m1 pro. The author says it took him 26 mins to brute force his friend key.

**Comment by stevealexrs** [comment]
Apple silicon mac gpu uses unified memory while Nvidia dGPU uses external memory (dedicated is 6GB only). Is it possible this slow it down?

**Comment by ytrezq** [comment]
> Apple silicon mac gpu uses unified memory while Nvidia dGPU uses external memory (dedicated is 6GB only). Is it possible this slow it down?

Not sure it uses Unified Memory. For those type of devices, while the memory is shared physically it s partitionned at the firmware level (on Intel you can even configure the split).
And anyway, memory is normally initialized directly on the gpu by the gpu.

**Comment by ytrezq** [comment]
Back to the original issue, I may found why or an additional problem.

Doesn’t this https://github.com/rebryk/profanity-brute-force/blob/b4e93566e7f414c91c899665216cf87fbd455393/profanity.cpp#L20 looks like to be a hardcoded value that won’t work on every systems ?

No idea on how to fix it though…
