### ISSUE TITLE
Wintermute 2 wallet private key search unsuccess

### ISSUE THREAD

**Issue by ghost** [rebryk/profanity-brute-force#2]
the well know wintermute 2 vanity drained address
[0x000002Cba8DfB0a86A47a415592835E17fac080a](https://etherscan.io/address/0x000002cba8dfb0a86a47a415592835e17fac080a) (Wintermute 2)

tx: 0x75c82e0a4d3a70c66e59332ca7db8f05d3a2b06164f4e3b4c9e39cb5565c4188
Returned Raw Transaction Hex :
0x01f86901830657ec8506fc23ac0082520894000002cba8dfb0a86a47a415592835e17fac080a8080c080a06715893792ea455d864ef1080c1de7124844fe08d212df264079bfd82ffbf947a07e02501f55cc1e812e4de3dc280880f0ea99cd0fe51849ef4969a3e1de5012e5
```
python pubkey.py -t 0x01f86901830657ec8506fc23ac0082520894000002cba8dfb0a86a47a415592835e17fac080a8080c080a06715893792ea455d864ef1080c1de7124844fe08d212df264079bfd82ffbf947a07e02501f55cc1e812e4de3dc280880f0ea99cd0fe51849ef4969a3e1de5012e5
Pubkey: 0xc720a841d3f9620912e07bb504372b9c77b86ebbf3d3f42ffe510142e939e4d6f832acd29ed5cd3db532bc901770894a637f0078e68a2341b9d4b39174b2764c
```

```
./profanity.x64 --reverse --steps 80000 --cache --target 0xc720a841d3f9
620912e07bb504372b9c77b86ebbf3d3f42ffe510142e939e4d6f832acd29ed5cd3db532bc901770894a637f0078e68a2341b9d4b39174b2764c
```

I increased the steps to 80000 but still didn't find the private key. what is the steps parameter up limit and how to set it as optimal?

**Comment by rebryk** [comment]
The number of steps required depends on the amount of time spent generating the wallet. So it really depends, but there is no limit.

**Comment by agoora** [comment]
How is it compiled for windows?
Thanks

**Comment by eulerbeat5** [comment]
@0xCuteSocks did you manage to find?

**Comment by CheapyFresh** [comment]
worked for me in less than 40000 steps....

**Comment by Web3Paradise** [comment]
> worked for me in less than 40000 steps....

can you give more details how you managed to make it work? and which computer were you using

**Comment by Web3Paradise** [comment]
> worked for me in less than 40000 steps....

Which config where you using? Gpu?

**Comment by ytrezq** [comment]
@Web3Paradise : what about doing it in the way of #18 instead ?

**Comment by wetdro** [comment]
try 220000
