### ISSUE TITLE
Segmentation fault (core dumped) on large steps

### ISSUE THREAD

**Issue by ghost** [rebryk/profanity-brute-force#3]
segfault around 194000 steps on batch 3

**Comment by eulerbeat5** [comment]
@0xCuteSocks what was the reason? lack of GPU memory?

**Comment by ghost** [comment]
hey @0xCuteSocks I've been running into segmentation fault on batch 3 as well, what was your solution?

**Comment by Web3Paradise** [comment]
> hey @0xCuteSocks I've been running into segmentation fault on batch 3 as well, what was your solution?

This is caused by lack of GPU memory, try on a card with 16gb

**Comment by ghost** [comment]
It seems like using 2 GPUs with 48gb of GPU the most steps I can request are 200000, I'm trying to run more like 1million steps, any advice on how much GPU memory I'll need?

**Comment by ghost** [comment]
actually I keep getting segmentation failed even on 200000 steps

**Comment by Web3Paradise** [comment]
> It seems like using 2 GPUs with 48gb of GPU the most steps I can request are 200000, I'm trying to run more like 1million steps, any advice on how much GPU memory I'll need?

The GPU memory limit is 8gb (used by the tool), and I don't think you can run on multiple GPU, it usually fail for me. You have to skip one gpu. 

I'm running this tool on Nvidia RTX 4090 with 24gb memory and it complete 500k steps easily within 3 hours (from batch 1 to 8). Unless you are trying to brute force 11 character, 1 million steps is enough on an RTX 4090

**Comment by ghost** [comment]
> > It seems like using 2 GPUs with 48gb of GPU the most steps I can request are 200000, I'm trying to run more like 1million steps, any advice on how much GPU memory I'll need?
> 
> The GPU memory limit is 8gb (used by the tool), and I don't think you can run on multiple GPU, it usually fail for me. You have to skip one gpu.
> 
> I'm running this tool on Nvidia RTX 4090 with 24gb memory and it complete 500k steps easily within 3 hours (from batch 1 to 8). Unless you are trying to brute force 11 character, 1 million steps is enough on an RTX 4090

Thanks! This seems to be working for me now, appreciate the help. I'm focusing on an address that has a palindrome (5 chars at start and end of address) so hoping 500000 steps will work.
